### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by kyouko-taiga**
This PR adds a test exercising the standard optimization passes of LLVM (i.e., `-O0`, `-O1`, ...)

### CODE REVIEW

**Comment by dabrahams** [comment]
👍

**Comment by dabrahams** [comment]
I guess you're not yet testing locally with an assert-enabled LLVM.  We [strongly recommend](https://github.com/hylo-lang/Swifty-LLVM?tab=readme-ov-file#llvm) that, y'know ;-)

**Comment by dabrahams** [comment]
@kyouko-taiga Currently it shows `ArrayType.count` to be [uncovered](https://app.codecov.io/gh/hylo-lang/Swifty-LLVM/pull/57?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=hylo-lang), but resolving the merge might make that go away.

**Comment by dabrahams** [comment]
@kyouko-taiga oh, the base branch is not `main`.  Don't know whether you realized that.

**Comment by kyouko-taiga** [comment]
I think that was intentional, because IIRC the code my additional test is building on that other PR and is an answer to [your comment](https://github.com/hylo-lang/Swifty-LLVM/pull/55#pullrequestreview-1941798539).

**Comment by kyouko-taiga** [comment]
Since I closed #55 I will salvage this PR to make it work with the "current" API design.

**Pull request closed without merging**
