### PR TITLE
Strict concurrency support

### PR DESCRIPTION
**Pull request by koliyo**
Allow using strict concurrency checking in downstream builds

### CODE REVIEW

**Comment by kyouko-taiga** [comment]
Hi, thanks for this PR. What is the purpose of this change?

**Comment by koliyo** [comment]
I was trying to activate strict concurrency checking in the Hylo LSP and got issues with non-sendable types in Hylo, and trying to fix this I ended up in Swifty-LLVM.

Maybe this is not the right approach, and perhaps I should not try to introduce Sendable in Hylo.

I am pretty new to swift and did get the recommendation to enable strict concurrency checking in my code. And I like the idea of using strict checking. But on the other hand, I could also enable this without changing dependencies (Hylo), and instead using `@preconcurrency` import.

So I guess it comes down to the following question: Are you guys interested in introducing strict concurrency checking in Hylo?

**Comment by kyouko-taiga** [comment]
I am skeptical that we'll ever want to use Swift's actor-based concurrency in our code base. So I would lean toward a no at this point.

**Comment by koliyo** [comment]
Alright, well in that case I don't see any reason to pursue this PR, I will handle things on my end instead!

**Comment by dabrahams** [comment]
@kyouko-taiga I think we should reconsider this PR.  It doesn't add enough complexity to be harmful, _provided that the types being marked `Sendable` actually satisfy the necessary semantic requirements_, and if it increases adoptability of Swifty-LLVM by other projects, that accrues to possible improvements and more public testing.  That would be a win, even if Hylo doesn't end up using this capability.

**Comment by kyouko-taiga** [comment]
I am reluctant because any feature we decide to support is an additional burden we have to cary as we go. That includes  understanding what semantic requirements are expected, which is completely foreign to me at the moment.

I am perfectly happy to spend the necessary efforts if they can serve an actual library user. If one reads these lines, please do not hesitate to re-open! Until then, I'd rather not add conformances to a protocol I do not currently understand.

**Comment by dabrahams** [comment]
I think things with value semantics automatically satisfy the semantic requirements `Sendable`. I was under the impression that @koliyo might be an "actual library user" if we would just accept the PR, and rejecting the PR just ensures we don't have an actual user who is using the capability.  Unless I've misunderstood that, rejecting the PR makes no sense to me, but I'm not going to fight for this.

**Comment by dabrahams** [comment]
This also might add a valuable compile-time defense against inadvertent reference semantics.

**Pull request closed without merging**
