### PR TITLE
Rough-and-ready context lifetime management.

### PR DESCRIPTION
**Pull request by dabrahams**
This is a mostly-mechanical change; careful review is required to make sure it's being done right.

### CODE REVIEW

**Comment by kyouko-taiga** [comment]
So IIUC, the idea is to hold a reference to the context in every data structure that it could manage. I think that will work but probably we need to guarantee more lifetimes than just that of the context. It's very likely that we also need to guarantee the lifetime of the module in which we create functions. In fact, I suppose pretty much every class that has a public destructor in C++ (and therefore a corresponding `XXXDispose` wrapper in the C API) needs some kind of lifetime management mechanism. So probably instructions would need to be written like this:

```swift
protocol InModule: Contextual { ... }
protocol Instruction: InModule { ... }
```

There's a lot of boilerplate involved in adding a reference to all of these data structures and I'm wondering if perhaps we should try a less clever approach. The context is a the most annoying object to track because it really doesn't fit nicely into a MVS-oriented wrapper. So my original idea was to hide `LLVMContext` under the rug. With the benefit of insights, however, I think it was a bad idea.

We need to use different contexts if we want to use LLVM in a multithreaded environment, which we'll probably want to do sooner than later (LLVM codegen currently takes ~10% of our compile time). So I guess at that point we'll want to uncouple the context from the module and write the code of a single thread in a lambda like:

```swift
queue.addOperation {
  SwiftyLLVM.withContext { (llvm) in
    // Emit some modules ...
  }
}
```

AFAICT, pretty much everything else is tied to the lifetime of a module. So perhaps we need to pull the same trick:

```swift
SwiftyLLVM.withContext { (llvm) in
  llvm.withNewModule("MyModule") { (m) in
    // Emit some functions ...
  }
}
```

Then we document that it is UB to use any context/module property outside of the corresponding closure and all existing data structures can remain as they are. In practice it shouldn't degrade the UX because I expect the common use case to look like this:

```swift
SwiftyLLVM.withContext { (llvm) in
  llvm.withNewModule("xyz") { (m) in emitModule(&m) }
}

func emitModule(_ m: inout SwfityLLVM.Module) {
  // Lifetime-extending closures shenanigans have no impact here
}
```

**Review by kyouko-taiga — COMMENTED** [review]
As I commented on the PR, I think that's a sound approach but we should also consider the lifetime of other "disposable" LLVM objects.

**Comment by dabrahams** [comment]
[This](https://github.com/apple/swift-llvm-bindings/blob/b9b825218a945e450cbaf740a980284b323e09ca/Sources/LLVM/LLVM_Utils.apinotes#L5-L8) is how Swift is doing it with C++ interop; not very principled.

**Comment by kyouko-taiga** [comment]
> not very principled.

Indeed, it feels "hacky".

**Comment by dabrahams** [comment]
@kyouko-taiga we should close this, then?

**Comment by kyouko-taiga** [comment]
Yes, let's close. I will submit another PR using the `withXXX` approach, hopefully this afternoon.

**Pull request closed without merging**
